NC-211
railflow/railflow_annotations pull request #1
Opened 2021-09-06 07:33 UTC by liuyang-123

2021-09-13 09:00 UTC, sergey-oplavin requested changes

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +	public void create_withNoPangolinAnnotations() throws Exception {
No "Pangolin" in this project

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		(new CustomTestNgReporter()).addCustomTagsFor(xmlBuffer, testResult);
Remove extra square brackets `()` in all test methods

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +	private ITestResult mockTestResult(final Class clazz) throws NoSuchMethodException, IOException {
Remove IOException as it's not being thrown

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		assertEquals(3, testrailIds.size());
Replace with 
`assertEquals(Arrays.asList(101, 102, 103), testrailIds);`

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		assertEquals(3, jiraIds.size());
Replace with comparing lists

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		assertEquals(3, testrailIds.size());
`assertEquals(Arrays.asList(201, 202, 103), testrailIds);`

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		assertEquals(2, jiraIds.size());
Replace with comparing lists

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/util/ArrayUtilsTest.java
> +		assertEquals(3, list.size());
Use  assertEquals with list (Arrays.asList("str1","str2", "str3")

2021-09-13 09:00 UTC, sergey-oplavin commented on src/test/java/io/railflow/annotations/util/ArrayUtilsTest.java
> +		final Integer[] integers = ArrayUtils.toIntegers(intArr);
assert with list

2021-09-13 09:13 UTC, sergey-oplavin commented
We should also add a github action to build and deploy the project

2021-09-15 02:43 UTC, liuyang-123 commented on src/main/java/io/railflow/annotations/testng/CustomTestNgReporter.java
> +	private <T> void addCustomTagsForArrays(final XMLStringBuffer xmlBuffer, final String tagName, final T[] array) {
Renamed

2021-09-15 02:43 UTC, liuyang-123 commented on src/main/java/io/railflow/annotations/testng/CustomTestNgReporter.java
> +	private static final String TAG_NAME_RAILFLOW = "railflow";
Renamed

2021-09-15 02:43 UTC, liuyang-123 commented on src/main/java/io/railflow/annotations/testng/CustomTestNgReporter.java
> +	private static final String PROPERTY_NAME_NAME = "name";
Renamed

2021-09-15 02:44 UTC, liuyang-123 commented on src/main/java/io/railflow/annotations/testng/CustomTestNgReporter.java
> +			return annotatedElement.isAnnotationPresent(Railflow.class) ? annotatedElement.getAnnotation((Railflow.class)) : null;
Removed

2021-09-15 02:44 UTC, liuyang-123 commented on src/main/java/io/railflow/annotations/testng/CustomTestNgReporter.java
> +			final AnnotatedElement annotatedElement = classSupplier.get();
Fixed

2021-09-15 02:44 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		assertEquals(3, jiraIds.size());
Fixed

2021-09-15 02:44 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		assertEquals(3, testrailIds.size());
Fixed

2021-09-15 02:44 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		assertEquals(2, jiraIds.size());
Fixed

2021-09-15 02:44 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/util/ArrayUtilsTest.java
> +		assertEquals(3, list.size());
Fixed

2021-09-15 02:44 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/util/ArrayUtilsTest.java
> +		final Integer[] integers = ArrayUtils.toIntegers(intArr);
Fixed

2021-09-15 09:52 UTC, liuyang-123 commented
> We should also add a github action to build and deploy the project
Added the action script to deploy to github repositories.

2021-09-15 09:53 UTC, liuyang-123 commented
> We should also add a github action to build and deploy the project

Added the action script to deploy to github repositories.

2021-09-17 08:22 UTC, liuyang-123 commented on src/main/java/io/railflow/annotations/util/ArrayUtils.java
> +public class ArrayUtils {
Removed

2021-09-17 08:24 UTC, liuyang-123 commented on src/main/java/io/railflow/annotations/util/ArrayUtils.java
> +public class ArrayUtils {
Removed because it's unused anymore

2021-09-17 09:22 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +	public void create_withNoPangolinAnnotations() throws Exception {
Fixed

2021-09-17 09:22 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +		(new CustomTestNgReporter()).addCustomTagsFor(xmlBuffer, testResult);
Fixed

2021-09-17 09:22 UTC, liuyang-123 commented on src/test/java/io/railflow/annotations/testng/CustomTestNgReporterTest.java
> +	private ITestResult mockTestResult(final Class clazz) throws NoSuchMethodException, IOException {
Removed

2021-09-29 17:32 UTC, merged